// export const themes = {
//   // neonGreen: {
//   //   name: 'neonGreen',
//   //   themeColor: '#39FF14',
//   //   background: '#0f0f1f',
//   //   text: '#FFFFFF',
//   // },
//   // neonRed: {
//   //   name: 'neonRed',
//   //   themeColor: '#FF3131',
//   //   background: '#0f0f1f',
//   //   text: '#FFFFFF',
//   // },
//   // neonBlue: {
//   //   name: 'neonBlue',
//   //   themeColor: '#0AB9F2',
//   //   background: '#0f0f1f',
//   //   text: '#FFFFFF',
//   // },
//   // neonPurple: {
//   //   name: 'neonPurple',
//   //   themeColor: '#9D00FF',
//   //   background: '#0f0f1f',
//   //   text: '#FFFFFF',
//   // },
//   // neonPink: {
//   //   name: 'neonPink',
//   //   themeColor: '#FF10F0',
//   //   background: '#0f0f1f',
//   //   text: '#FFFFFF',
//   // },
//   // neonOrange: {
//   //   name: 'neonOrange',
//   //   themeColor: '#FF6700',
//   //   background: '#0f0f1f',
//   //   text: '#FFFFFF',
//   // },
//   // neonMagenta: {
//   //   name: 'neonMagenta',
//   //   themeColor: '#FF00FF',
//   //   background: '#0f0f1f',
//   //   text: '#FFFFFF',
//   // },
//   // neonTurquoise: {
//   //   name: 'neonTurquoise',
//   //   themeColor: '#30D5C8',
//   //   background: '#0f0f1f',
//   //   text: '#FFFFFF',
//   // },
//   // neonViolet: {
//   //   name: 'neonViolet',
//   //   themeColor: '#8F00FF',
//   //   background: '#0f0f1f',
//   //   text: '#FFFFFF',
//   // },
//   // neonGold: {
//   //   name: 'neonGold',
//   //   themeColor: '#FFD700',
//   //   background: '#0f0f1f',
//   //   text: '#FFFFFF',
//   // },
//   // neonLime: {
//   //   name: 'neonLime',
//   //   themeColor: '#CCFF00',
//   //   background: '#0f0f1f',
//   //   text: '#FFFFFF',
//   // },
//   // neonYellow: {
//   //   name: 'neonYellow',
//   //   themeColor: '#FFFF00',
//   //   background: '#0f0f1f',
//   //   text: '#000000', // Dark text for contrast
//   // },
//   // neonCyan: {
//   //   name: 'neonCyan',
//   //   themeColor: '#00FFFF',
//   //   background: '#0f0f1f',
//   //   text: '#000000', // Dark text for contrast
//   // },
//   // neonWhite: {
//   //   name: 'neonWhite',
//   //   themeColor: '#FFFFFF',
//   //   background: '#0f0f1f',
//   //   text: '#000000', // Dark text for contrast
//   // },
// };

export const themes = {
  neonGreen: {
    name: 'neonGreen',
    themeColor: '#39FF14',
    background: '#0f0f1f',
    text: '#FFFFFF',
    primary: '#39FF14',
    secondary: '#0aff9d',
    placeholder: '#80ffab',
    inputBackground: '#1a1a2e',
    border: '#39FF14',
    buttonText: '#000000',
    link: '#39FF14',
  },
  neonRed: {
    name: 'neonRed',
    themeColor: '#FF3131',
    background: '#0f0f1f',
    text: '#FFFFFF',
    primary: '#FF3131',
    secondary: '#ff6666',
    placeholder: '#ff9999',
    inputBackground: '#1a1a2e',
    border: '#FF3131',
    buttonText: '#000000',
    link: '#FF3131',
  },
  neonBlue: {
    name: 'neonBlue',
    themeColor: '#0AB9F2',
    background: '#0f0f1f',
    text: '#FFFFFF',
    primary: '#0AB9F2',
    secondary: '#70d6ff',
    placeholder: '#b3eaff',
    inputBackground: '#1a1a2e',
    border: '#0AB9F2',
    buttonText: '#000000',
    link: '#0AB9F2',
  },
  neonPurple: {
    name: 'neonPurple',
    themeColor: '#9D00FF',
    background: '#0f0f1f',
    text: '#FFFFFF',
    primary: '#9D00FF',
    secondary: '#c770ff',
    placeholder: '#dbaaff',
    inputBackground: '#1a1a2e',
    border: '#9D00FF',
    buttonText: '#FFFFFF',
    link: '#9D00FF',
  },
  neonPink: {
    name: 'neonPink',
    themeColor: '#FF10F0',
    background: '#0f0f1f',
    text: '#FFFFFF',
    primary: '#FF10F0',
    secondary: '#ff5ff5',
    placeholder: '#ffaaff',
    inputBackground: '#1a1a2e',
    border: '#FF10F0',
    buttonText: '#000000',
    link: '#FF10F0',
  },
  neonOrange: {
    name: 'neonOrange',
    themeColor: '#FF6700',
    background: '#0f0f1f',
    text: '#FFFFFF',
    primary: '#FF6700',
    secondary: '#ff944d',
    placeholder: '#ffc299',
    inputBackground: '#1a1a2e',
    border: '#FF6700',
    buttonText: '#000000',
    link: '#FF6700',
  },
  neonMagenta: {
    name: 'neonMagenta',
    themeColor: '#FF00FF',
    background: '#0f0f1f',
    text: '#FFFFFF',
    primary: '#FF00FF',
    secondary: '#ff66ff',
    placeholder: '#ffb3ff',
    inputBackground: '#1a1a2e',
    border: '#FF00FF',
    buttonText: '#000000',
    link: '#FF00FF',
  },
  neonTurquoise: {
    name: 'neonTurquoise',
    themeColor: '#30D5C8',
    background: '#0f0f1f',
    text: '#FFFFFF',
    primary: '#30D5C8',
    secondary: '#66f0e6',
    placeholder: '#b3fff9',
    inputBackground: '#1a1a2e',
    border: '#30D5C8',
    buttonText: '#000000',
    link: '#30D5C8',
  },
  neonViolet: {
    name: 'neonViolet',
    themeColor: '#8F00FF',
    background: '#0f0f1f',
    text: '#FFFFFF',
    primary: '#8F00FF',
    secondary: '#b266ff',
    placeholder: '#dbb3ff',
    inputBackground: '#1a1a2e',
    border: '#8F00FF',
    buttonText: '#FFFFFF',
    link: '#8F00FF',
  },
  neonGold: {
    name: 'neonGold',
    themeColor: '#FFD700',
    background: '#0f0f1f',
    text: '#FFFFFF',
    primary: '#FFD700',
    secondary: '#ffe066',
    placeholder: '#fff2b3',
    inputBackground: '#1a1a2e',
    border: '#FFD700',
    buttonText: '#000000',
    link: '#FFD700',
  },
  neonLime: {
    name: 'neonLime',
    themeColor: '#CCFF00',
    background: '#0f0f1f',
    text: '#FFFFFF',
    primary: '#CCFF00',
    secondary: '#e6ff66',
    placeholder: '#f2ffb3',
    inputBackground: '#1a1a2e',
    border: '#CCFF00',
    buttonText: '#000000',
    link: '#CCFF00',
  },
  neonYellow: {
    name: 'neonYellow',
    themeColor: '#FFFF00',
    background: '#0f0f1f',
    text: '#000000',
    primary: '#FFFF00',
    secondary: '#ffff66',
    placeholder: '#ffffb3',
    inputBackground: '#333333',
    border: '#FFFF00',
    buttonText: '#000000',
    link: '#FFFF00',
  },
  neonCyan: {
    name: 'neonCyan',
    themeColor: '#00FFFF',
    background: '#0f0f1f',
    text: '#000000',
    primary: '#00FFFF',
    secondary: '#66ffff',
    placeholder: '#b3ffff',
    inputBackground: '#333333',
    border: '#00FFFF',
    buttonText: '#000000',
    link: '#00FFFF',
  },
};

